<?php
// $Id$

define('WORDPRESS_MIGRATE_ACCESS_MIGRATE', 'migrate wordpress blogs');
define('WORDPRESS_MIGRATE_ACCESS_CONFIGURE', 'configure wordpress migration');

/**
 * @file
 * API and drush commands to support migration of data from WordPress
 * into a Drupal installation.
 */

/**
 * Implements hook_permission().
 */
function wordpress_migrate_permission() {
  return array(
    WORDPRESS_MIGRATE_ACCESS_MIGRATE => array(
      'title' => t('Migrate WordPress blogs into Drupal'),
    ),
    WORDPRESS_MIGRATE_ACCESS_CONFIGURE => array(
      'title' => t('Configure migration of WordPress blogs'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function wordpress_migrate_menu() {
  $items = array();

  $items['admin/content/wordpress'] = array(
    'title' => 'WordPress migration',
    'description' => 'Migrate WordPress content into Drupal',
    'page callback' => 'wordpress_migrate_import',
    'access arguments' => array(WORDPRESS_MIGRATE_ACCESS_MIGRATE),
    'file' => 'wordpress_migrate.pages.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/content/wordpress/configure'] = array(
    'title' => 'WordPress migration configuration',
    'description' => 'Configure WordPress migration into Drupal',
    'page callback' => 'wordpress_migrate_configure',
    'access arguments' => array(WORDPRESS_MIGRATE_ACCESS_CONFIGURE),
    'file' => 'wordpress_migrate.pages.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * Implementation of hook_migrate_api().
 */
function wordpress_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

function _wordpress_machine_from_title($class_name, $title) {
  return $title . substr($class_name, strlen('WordPress'),
    strlen($class_name) - strlen('WordPress'));
}

/**
 * Implementation of hook_mail().
 *
 * @param $key
 * @param $message
 * @param $params
 */
function wordpress_migrate_mail($key, &$message, $params) {
  $data['user'] = $params['account'];
  $options['language'] = $message['language'];
  $variables = array();
  user_mail_tokens($variables, $data, $options);
  $langcode = $message['language']->language;
  switch ($key) {
    case 'import_complete':
      $subject = variable_get('wordpress_migrate_notification_subject', '');
      $body = variable_get('wordpress_migrate_notification_body', '');
      $message['subject'] = t($subject, $variables, array('langcode' => $langcode));
      $message['body'][] = t($body, $variables, array('langcode' => $langcode));
      break;
  }
}
